### ISSUE TITLE
API llb

### ISSUE THREAD

**Issue by toastxc** [Catasterphe/RevoltSpotifyStatus#5]
Hi :3
Is there a reason why you've opted to not use a revolt wrapper? 
There are quite a few options out there.

**Comment by Catasterphe** [comment]
hi @toastxc , no there's no reason I just wanted to do it without any wrappers lol

**Comment by toastxc** [comment]
Cool ^^
enjoy

**Comment by toastxc** [comment]
Although if you want help with that just ask.
